apiVersion: v1
kind: Secret
metadata:
  name: spark-consumer-secrets
  namespace: bigdata
  labels:
    app: spark-streaming-consumer
type: Opaque
stringData:
  INFLUXDB_TOKEN: "wCXJQbt3yjykKYrnVxSrjkXFnQ0fv0p2UIer4Z8j0bOkKfPId_3n_LgZa-5TQ9ElOI8TWQ7GFrf0xFCWcRPkCg=="
