apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-consumer-config
  namespace: bigdata
  labels:
    app: spark-streaming-consumer
data:
  KAFKA_INTERNAL_SERVERS: "kafka-broker-0.kafka-broker-headless.bigdata.svc.cluster.local:9092"
  WEATHER_KAFKA_TOPIC: "weather-data"
  INFLUXDB_SERVER: "http://influxdb.bigdata.svc.cluster.local:8086"
  INFLUXDB_BUCKET: "primary"
  INFLUXDB_ORG: "primary"
  INFLUXDB_MEASUREMENT: "weather-data"
  HDFS_OUTPUT_PATH: "hdfs://hdfs-namenode:8020/weather-data"
