apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: bigdata
  labels:
    app: grafana
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb.bigdata.svc.cluster.local:8086
        jsonData:
          version: Flux
          organization: primary
          defaultBucket: primary
          tlsSkipVerify: true
          httpMode: POST
        secureJsonData:
          token: ${INFLUXDB_TOKEN}
