apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: bigdata
  labels:
    app: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin123"
