apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: bigdata
  labels:
    app: influxdb
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD: "admin123"
  DOCKER_INFLUXDB_INIT_ORG: "primary"
  DOCKER_INFLUXDB_INIT_BUCKET: "primary"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "wCXJQbt3yjykKYrnVxSrjkXFnQ0fv0p2UIer4Z8j0bOkKfPId_3n_LgZa-5TQ9ElOI8TWQ7GFrf0xFCWcRPkCg=="
